### ISSUE TITLE
sysupgrade not working ?

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#10]
root@openwrt-x86:/tmp# sysupgrade -n lede-2016-08-19-x86-generic-combined-ext4.img.gz
Sending TERM to remaining processes ... ubusd askfirst askfirst logd rpcd netifd odhcpd crond php-fpm /sbin/sysupgrade: line 237: can't open /proc/1420/cmdline: no such file
php-fpm uhttpd smbd nmbd unbound nginx ss-redir ss-tunnel /sbin/sysupgrade: line 237: can't open /proc/1734/cmdline: no such file
nginx vlmcsd ntpd aria2c dnsmasq dynamic_dns_upd
Sending KILL to remaining processes ... askfirst askfirst
Switching to ramdisk...
Performing system upgrade...
Reading partition table from bootdisk...
Invalid partition table on /dev/sdb2

**Comment by debiansid** [comment]
Device     Boot   Start      End  Sectors  Size Id Type
/dev/sdb1  \*        512     8703     8192    4M 83 Linux
/dev/sdb2          9216   533503   524288  256M 83 Linux
/dev/sdb3        534528  4728831  4194304    2G 82 Linux swap / Solaris
/dev/sdb4       4728832 15613919 10885088  5.2G 83 Linux

**Comment by wongsyrone** [comment]
X86我不太清楚，那部分全是官方的修改

**Comment by debiansid** [comment]
哪里可以问道？

**Comment by wongsyrone** [comment]
邮件列表

**Comment by debiansid** [comment]
ok,可以用工具写到cf卡里去启动。应该是sysupgrade broken
