### ISSUE TITLE
Mptcp patch 

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#11]
Any plan on this?
http://mytechpg.blogspot.com/2016/01/multipath-tcp-how-to-test-mptcp-with.html

**Comment by wongsyrone** [comment]
应该需要内核补丁，目前还没看

**Comment by debiansid** [comment]
https://github.com/ovh/overthebox-feeds

**Comment by wongsyrone** [comment]
这个用途是干嘛

**Comment by debiansid** [comment]
https://www.multipath-tcp.org
好像ss libev已经支持

**Comment by debiansid** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/756

**Comment by wongsyrone** [comment]
unstable
