### ISSUE TITLE
install wongsryone feeds against 3.18 with glibc2.21 error

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#13]
I am going to install your feeds against overthehost openwrt(mptcp patched), I got this error and unable to install ssh server, would you please check it for me?

thanks

OpenWrt-libtool: install: (cd /home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/modules/pam_exec; /bin/bash /home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/libtool  --tag CC --mode=relink x86_64-openwrt-linux-gnu-gcc -I../../libpam/include -I../../libpamc/include -Os -pipe -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -fpic -W -Wall -Wbad-function-cast -Wcast-align -Wcast-qual -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wstrict-prototypes -Wwrite-strings -Winline -Wshadow -no-undefined -avoid-version -module -Wl,--version-script=./../modules.map -L/home/storage/overthebox/overthebox-openwrt/staging_dir/target-x86_64_glibc-2.21/usr/lib -L/home/storage/overthebox/overthebox-openwrt/staging_dir/target-x86_64_glibc-2.21/lib -L/home/storage/overthebox/overthebox-openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_glibc-2.21/usr/lib -L/home/storage/overthebox/overthebox-openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_glibc-2.21/lib -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -o pam_exec.la -rpath /lib/security pam_exec.lo ../../libpam/libpam.la -inst-prefix-dir /home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/ipkg-install)
OpenWrt-libtool: relink: x86_64-openwrt-linux-gnu-gcc -shared  -fPIC -DPIC .libs/pam_exec.la.lnkscript  -L/home/storage/overthebox/overthebox-openwrt/staging_dir/target-x86_64_glibc-2.21/usr/lib -L/home/storage/overthebox/overthebox-openwrt/staging_dir/target-x86_64_glibc-2.21/lib -L/home/storage/overthebox/overthebox-openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_glibc-2.21/usr/lib -L/home/storage/overthebox/overthebox-openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_glibc-2.21/lib -L/home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/ipkg-install/lib -lpam -ldl  -Os -Wl,--version-script=./../modules.map -Wl,--as-needed -Wl,--no-undefined -Wl,-O1   -Wl,-soname -Wl,pam_exec.so -o .libs/pam_exec.so
.libs/pam_exec.o: In function `call_exec':
pam_exec.c:(.text+0x6f1): undefined reference to`pam_modutil_sanitize_helper_fds'
collect2: error: ld returned 1 exit status
OpenWrt-libtool: install: error: relink `pam_exec.la' with the above command before installing it
Makefile:618: recipe for target 'install-securelibLTLIBRARIES' failed
make[7]: **\* [install-securelibLTLIBRARIES] Error 1
make[7]: Leaving directory '/home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/modules/pam_exec'
Makefile:992: recipe for target 'install-am' failed
make[6]: **\* [install-am] Error 2
make[6]: Leaving directory '/home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/modules/pam_exec'
Makefile:428: recipe for target 'install-recursive' failed
make[5]: **\* [install-recursive] Error 1
make[5]: Leaving directory '/home/storage/overthebox/overthebox-openwrt/build_dir/target-x86_64_glibc-2.21/Linux-PAM-1.2.0/modules'
Makefile:476: recipe for target 'install-recursive' failed

**Comment by wongsyrone** [comment]
No support will be provided if you use repos not maintained by myself.

**Comment by debiansid** [comment]
I change libpam version to 1.18, it works
