### ISSUE TITLE
shadowsocks-libev 2.5.0

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#14]
https://github.com/shadowsocks/shadowsocks-libev/commit/7c76026791359dd895a485e36134b3b40c2fc43a

**Comment by wongsyrone** [comment]
这个更改只影响服务端，所以暂时没有更新的必要。目前版本为https://github.com/shadowsocks/shadowsocks-libev/commit/9a43cc6e6b61d16c157d53ab7f22a34ae61a9bc4
