### ISSUE TITLE
Modify overthebox

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#15]
https://github.com/ovh/overthebox-openwrt

这个可以聚合多条链路 但是不支持modem bridge mode,目前不支持其他运营商 
你看看能改来支持国内运营商的adsl 就好了

**Comment by wongsyrone** [comment]
应该需要https://github.com/wongsyrone/lede-1/issues/11 ， 暂时不考虑支持。

**Comment by debiansid** [comment]
它的内核补丁已经打好了的

**Comment by wongsyrone** [comment]
不不不，他只是给3.18打好补丁，不过4.4和3.18差别太大，而且他那个补丁太巨大了，还是等进入主线再说吧。

**Comment by debiansid** [comment]
主要mptcp最新版目前才支持4.1.25，想早点用上mptcp只能用3.18

**Comment by wongsyrone** [comment]
目前没有支持旧内核打算
