### ISSUE TITLE
kernel panic

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#16]
sorry to spam here. I filed bug on bugs.lede-project.org, looks like no one is taking care of that.

after r1442, kenerl panic on every commit. any idea how to checkout r1442?

**Comment by wongsyrone** [comment]
Since you didn't provide any info that helps to determine the issue, it is expected to be ignored. 
ref: https://bugs.lede-project.org/index.php?do=details&task_id=169
