### ISSUE TITLE
你好,请教下musl SDK环境怎么编译mbdetls

### ISSUE THREAD

**Issue by juyyao** [wongsyrone/lede-1#18]
我这边编译错误是MBEDTLS_CIPHER_MODE_CFB required
已经加了你提供的patch并重新编译了mbedtls,但是还是提示这个错误,该从哪里下手解决呢?谢谢

**Comment by wongsyrone** [comment]
SDK我不太清楚，我都是代码树直接编译的。也可能你改了patch没有clean，用了旧的，因为这个部分是由Makefile的InstallDev处理的，包含的头文件是引用的staging_dir里面的，你看看那个是否发生了变化。

**Comment by juyyao** [comment]
好的 我这边代码树尝试下 谢谢
