### ISSUE TITLE
源码编译错误求助

### ISSUE THREAD

**Issue by juyyao** [wongsyrone/lede-1#19]
git下来整个源码 才make就错误,求助下

juyyao@debian:~/down/lede$ make with -j1 V=s
File [/home/juyyao/down/lede/tmp/.config] already exists, skipping it !
/!\ THE FOLLOWING FILES WERE _NOT_ SUCCESSFULY COPIED:
##     - /home/juyyao/down/lede/.config

Please check journal: /home/juyyao/.gcp/journal
make[1]: Entering directory '/home/juyyao/down/lede'
make[1]: **\* No rule to make target 'with'.  Stop.
make[1]: Leaving directory '/home/juyyao/down/lede'
/home/juyyao/down/lede/include/toplevel.mk:193: recipe for target 'with' failed
make: **\* [with] Error 2

**Comment by wongsyrone** [comment]
你确定这个命令对？`make with -j1 V=s`

**Comment by juyyao** [comment]
嗯~一直是提示下面这个错误的 然后想看下错误过程复制错了 
make -j1 V=s之后
Usage: 
        cp [options] FILE DEST
        cp [options] FILE1 [FILE2 ...] DEST-DIR

```
    cp --help for options list
```

cp: error: no such option: -p

**Comment by juyyao** [comment]
卸载gcp后解决了~
