### ISSUE TITLE
测试完，vlmcsd会报错！！

### ISSUE THREAD

**Issue by oe77** [wongsyrone/lede-1#2]
make[3]: Entering directory '/home/lo/1/openwrt15.05.1-1/feeds/extra/packages/vlmcsd'
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -D_PEDANTIC -ffunction-sections -fdata-sections -flto  -I/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include -I/home/lo/1/openwrt15.05.1-1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/lo/1/openwrt15.05.1-1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -D_PEDANTIC -ffunction-sections -fdata-sections -flto  -I/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/include -I/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/include -I/home/lo/1/openwrt15.05.1-1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/home/lo/1/openwrt15.05.1-1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include " LDFLAGS="-L/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/lo/1/openwrt15.05.1-1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/lo/1/openwrt15.05.1-1/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib -Wl,--gc-sections -Wl,-flto " make -j1 -C /home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818/. AR="mipsel-openwrt-linux-uclibc-gcc-ar" AS="mipsel-openwrt-linux-uclibc-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -D_PEDANTIC -ffunction-sections -fdata-sections -flto" LD=mipsel-openwrt-linux-uclibc-ld NM="mipsel-openwrt-linux-uclibc-gcc-nm" CC="mipsel-openwrt-linux-uclibc-gcc" GCC="mipsel-openwrt-linux-uclibc-gcc" CXX="mipsel-openwrt-linux-uclibc-g++" RANLIB="mipsel-openwrt-linux-uclibc-gcc-ranlib" STRIP=mipsel-openwrt-linux-uclibc-strip OBJCOPY=mipsel-openwrt-linux-uclibc-objcopy OBJDUMP=mipsel-openwrt-linux-uclibc-objdump SIZE=mipsel-openwrt-linux-uclibc-size CROSS="mipsel-openwrt-linux-uclibc-" ARCH="mipsel" VERBOSE=3  ;
make[4]: Entering directory '/home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818'
make[4]: **\* No targets specified and no makefile found.  Stop.
make[4]: Leaving directory '/home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818'
Makefile:62: recipe for target '/home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818/.built' failed
make[3]: **\* [/home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818/.built] Error 2
make[3]: Leaving directory '/home/lo/1/openwrt15.05.1-1/feeds/extra/packages/vlmcsd'
package/Makefile:191: recipe for target 'package/feeds/extra/vlmcsd/compile' failed
make[2]: **\* [package/feeds/extra/vlmcsd/compile] Error 2
make[2]: Leaving directory '/home/lo/1/openwrt15.05.1-1'
package/Makefile:188: recipe for target '/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: **\* [/home/lo/1/openwrt15.05.1-1/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lo/1/openwrt15.05.1-1'
/home/lo/1/openwrt15.05.1-1/include/toplevel.mk:181: recipe for target 'world' failed

**Comment by wongsyrone** [comment]
> make[4]: **\* No targets specified and no makefile found. Stop.

你命令输错了，应该是 make package/vlmcsd/{clean,compile} V=99

**Comment by oe77** [comment]
命令应该无错吧，make V=99 ！！因为找不到某些文件所以出错了
make[4]: Entering directory '/home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818'

> make[4]: **\* No targets specified and no makefile found. Stop.

make[4]: Leaving directory '/home/lo/1/openwrt15.05.1-1/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/vlmcsd/vlmcsd-svn818'

**Comment by wongsyrone** [comment]
make menuconfig 打开了么

**Comment by oe77** [comment]
@wongsyrone 可以了！
