### ISSUE TITLE
Samab4 missing "renice" selection

### ISSUE THREAD

**Issue by Andy2244** [wongsyrone/lede-1#24]
The samba4 init rely on the "renice" selection in busybox and is missing by default.

Just add this to the makefile:
```
define Package/samba44-server/config
	select BUSYBOX_CONFIG_RENICE
endef
```

**Comment by wongsyrone** [comment]
already added https://github.com/wongsyrone/lede-1/blob/master/package/utils/busybox/Config-defaults.in#L2541

**Comment by Andy2244** [comment]
ah right sorry, i compile against the org. LEDE repo and just grab the packages i want from your repo manually. So i have to add this, since LEDE has this not set.

**Comment by wongsyrone** [comment]
OK. Closing.
