### ISSUE TITLE
extra samba 4 and 4.5.1 patches

### ISSUE THREAD

**Issue by Andy2244** [wongsyrone/lede-1#26]
Here are some of my extra samba patches, maybe you find those useful.

912/913: samba 4.x, changes the "msg.sock" location from nvram to the lockdir location on /tmp, to reduce nvram wear.
911: is a fix for samba 4.5.1 and some missing musl defines

[extra samba patches.zip](https://github.com/wongsyrone/lede-1/files/588847/extra.samba.patches.zip)

**Comment by inspector-ambitious** [comment]
@Andy2244 did you manage to get samba 4.5.1 to compile ?

**Comment by Andy2244** [comment]
@yhwh, yes i run Samba4 without problems for a while now and currently i run 4.6.2. Here is my personal package feed including the changes for samba and softether vpn, mainly patched to write to the Temp filesystem (ram) and reduce nvram wear.

[myfeed.zip.pdf](https://github.com/wongsyrone/lede-1/files/978339/myfeed.zip.pdf)

Keep in mind that we use simple predefined answer defines in the makefile, those work at least with the arm chips in the linksys WRT1200/1900 line. This is hacky, but should work for a lot of other router chips, yet is not the "right" way to-do it. Buildroot.org has implemented a proper way by using qemu to actually get those answers from the emulated environment. My version works for me and i did not want to spend the time porting there samba/qemu makefiles to lede/openwrt, which would be ideal.


PS: I could not add a zip, for whatever reasons so rename the file...

**Comment by wongsyrone** [comment]
The answers are just like https://github.com/lede-project/source/tree/master/include/site, A not-so-good way is to generate answers using qemu and rename them to "answer.$(ARCH).txt" and pick the correct one based on the variable.

**Comment by zhouruixi** [comment]
@Andy2244 Thanks for your feeds,but when I use your feeds to compile samba4 with LEDE 17.01 I got some errors

> Checking for Python version >= 2.6.0                                              : ok 2.7.13 
Checking for library python2.7                                                    : yes 
Checking for program python2.7-config                                             : /mnt/source_code/LEDE/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/usr/bin/python2-config 
Checking for custom code                                                          : Could not find the python development headers 
/mnt/source_code/LEDE/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/samba-4.6.2/wscript:109: error: the configuration failed (see '/mnt/source_code/LEDE/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/samba-4.6.2/bin/config.log')
make[3]: *** [/mnt/source_code/LEDE/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/samba-4.6.2/.configured_yyyyyyy] Error 1
make[3]: Leaving directory `/mnt/source_code/LEDE/package/myfeed/samba45'
make[2]: *** [package/myfeed/samba45/compile] Error 2
make[2]: Leaving directory `/mnt/source_code/LEDE'
make[1]: *** [/mnt/source_code/LEDE/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory `/mnt/source_code/LEDE

`````````````````````````````````````````````````````````````````````````````````````````
## tail /mnt/source_code/LEDE-samba4/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/samba-4.4.2/bin/config.log
> 
Checking for custom code
==>

#include "Python.h"
#ifdef __cplusplus
extern "C" {
#endif
        void Py_Initialize(void);
        void Py_Finalize(void);
#ifdef __cplusplus
}
#endif
int main()
{
   Py_Initialize();
   Py_Finalize();
   return 0;
}

<==
[1/2] Compiling test.c
../test.c:2:20: fatal error: Python.h: No such file or directory
compilation terminated.
['arm-openwrt-linux-muslgnueabi-gcc', '-Os', '-pipe', '-mcpu=cortex-a9', '-mfpu=vfpv3-d16', '-fno-caller-saves', '-fno-plt', '-fhonour-copts', '-Wno-error=unused-but-set-variable', '-Wno-error=unused-result', '-mfloat-abi=hard', '-iremap', '/mnt/source_code/LEDE/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/samba-4.6.2:samba-4.6.2', '-Wformat', '-Werror=format-security', '-fstack-protector', '-D_FORTIFY_SOURCE=1', '-Wl,-z,now', '-Wl,-z,relro', '-ffunction-sections', '-fdata-sections', '-Wno-deprecated-declarations', '-MD', '-fno-strict-aliasing', '-I/mnt/source_code/LEDE/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/usr/include', '-I/mnt/source_code/LEDE/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.16_eabi/include', '-I/mnt/source_code/LEDE/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/usr/include', '-I/mnt/source_code/LEDE/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/include/fortify', '-I/mnt/source_code/LEDE/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl-1.1.16_eabi/include', '-I/usr/local/include', '-I/usr/include/python2.7', '-D_SAMBA_BUILD_=4', '-DHAVE_CONFIG_H=1', '-D_GNU_SOURCE=1', '-D_XOPEN_SOURCE_EXTENDED=1', '../test.c', '-c', '-o', 'default/test_1.o']
command returned 'Build failed:  -> task failed (err #1): \n\t{task: cc test.c -> test_1.o}'Could not find the python development headers

**Comment by Andy2244** [comment]
@zhouruixi You need to make sure you use the custom python package as well, which should be the same as wongsyrone version. There are some samba specific changes in it.

Here is my script to add the myfeed dir to lede, so make sure the included python version is linked under .\package\feeds\myfeed:
```
#!/bin/bash

./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
./scripts/feeds install -a -f -p myfeed packages
```
My feeds.conf.default looks like this:
```
src-git luci https://git.lede-project.org/project/luci.git
src-link myfeed ../myfeed
src-git packages https://git.lede-project.org/feed/packages.git
```

I just build a new version 2 days ago with samba 4.6.3 and all worked fine useing myfeed + Lede master branch. I'm building under a 32bit Manjaro Arch btw.

PS: In my own Lede build doc there is a comment about python, but i think thats arch specific.
```
# symlink (/usr/bin/Pyhton -> Python2) (/usr/bin/Python-config -> python2-config) #arch host problem
> sudo ln -sf /usr/bin/python2 /usr/bin/python
> sudo ln -sf /usr/bin/python2-config /usr/bin/python-config
```

**Comment by zhouruixi** [comment]
@Andy2244  Hi,thanks for your help. And I had compile  samba4 with centos 7 64bit, OpenSUSE 42 64bit, debian 8 32bit by your step, but they all failed. I really don't know what's wrong! manjaro (arch linx) 32bit is necessary? I'll try fedora 25 next that manjaro can't install with Hyper-V.
BTW your feed installed correctly.

Is it possible for python version reasons?What's your python version?
centos 7 :   python-2.7.5
debian 8 :   python-2.7.9
OpenSUSE: python-2.7.12
fedora 25  : python-2.7.13

## OpenSUSE 64bit

> [1/2] Compiling ^[[32mtest.c^[[0m
In file included from /usr/include/python2.7/Python.h:58:0,
                 from ../test.c:2:
/usr/include/python2.7/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^

## debian 8 32bit

> [1/2] Compiling ^[[32mtest.c^[[0m
In file included from /usr/include/python2.7/Python.h:8:0,
                 from ../test.c:2:
/usr/include/python2.7/pyconfig.h:13:54: fatal error: arm-linux-gnueabihf/python2.7/pyconfig.h: No such file or directory
compilation terminated.

## centos 64bit

> [1/2] Compiling ^[[32mtest.c^[[0m
In file included from /usr/include/python2.7/Python.h:8:0,
                 from ../test.c:2:
/usr/include/python2.7/pyconfig.h:8:2: error: #error "Unknown word size"
 #error "Unknown word size"
  ^
In file included from /usr/include/python2.7/pyport.h:4:0,
                 from /usr/include/python2.7/Python.h:58,
                 from ../test.c:2:
/usr/include/python2.7/pyconfig.h:8:2: error: #error "Unknown word size"
 #error "Unknown word size"
  ^
In file included from /usr/include/python2.7/Python.h:58:0,
                 from ../test.c:2:
/usr/include/python2.7/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^
In file included from /usr/include/python2.7/pymath.h:4:0,
                 from /usr/include/python2.7/Python.h:77,
                 from ../test.c:2:
/usr/include/python2.7/pyconfig.h:8:2: error: #error "Unknown word size"
 #error "Unknown word size"
  ^

**Comment by Andy2244** [comment]
[andy@manjaro ~]$ python -V
Python 3.6.0
[andy@manjaro ~]$ python2 -V
Python 2.7.13
[andy@manjaro ~]$ uname -a
Linux manjaro 4.6.0-1-MANJARO 1 SMP PREEMPT Mon May 16 07:37:25 UTC 2016 i686 GNU/Linux
[andy@manjaro ~]$ gcc -v
gcc version 6.3.1 20170306 (GCC)

**Comment by zhouruixi** [comment]
I had compile samba 4.6.3 successfully with debian 8.And the reason why I am failed is the command below is missing  '-I/home/cc/lede-2T/lede/a-smb/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include/python2.7',

`['arm-openwrt-linux-muslgnueabi-gcc', '-Os', '-pipe', '-mcpu=cortex-a9', '-mfpu=vfpv3-d16', '-fno-caller-saves', '-fno-plt', '-fhonour-copts', '-Wno-error=unused-but-set-variable', '-Wno-error=unused-result', '-mfloat-abi=hard', '-iremap/home/cc/lede-2T/lede/a-smb/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/samba-4.6.2:samba-4.6.2', '-Wformat', '-Werror=format-security', '-fstack-protector', '-D_FORTIFY_SOURCE=1', '-Wl,-z,now', '-Wl,-z,relro', '-ffunction-sections', '-fdata-sections', '-Wno-deprecated-declarations', '-MD', '-fno-strict-aliasing', '-I/home/cc/lede-2T/lede/a-smb/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr/include', '-I/home/cc/lede-2T/lede/a-smb/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/include', '-I/home/cc/lede-2T/lede/a-smb/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl_eabi/usr/include', '-I/home/cc/lede-2T/lede/a-smb/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl_eabi/include/fortify', '-I/home/cc/lede-2T/lede/a-smb/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.4.0_musl_eabi/include', '-I/usr/local/include', '-I/usr/include/python2.7', '-D_SAMBA_BUILD_=4', '-DHAVE_CONFIG_H=1', '-D_GNU_SOURCE=1', '-D_XOPEN_SOURCE_EXTENDED=1', '../test.c', '-c', '-o', 'default/test_1.o']`

PS:When I use the python development headers which provide by python-dev(debian's package) ,I'll got" fatal error: arm-linux-gnueabihf/python2.7/pyconfig.h: No such file or directory",so,the python development headers must provide by the custom python.

Thanks for all working on samba 4 !

**Comment by Andy2244** [comment]
If still interested here is my current 4.7 version, that has adapted @hbl0307106015 changes, mainly removing python via "--disable-python".

[myfeed.zip](https://github.com/wongsyrone/lede-1/files/1327333/myfeed.zip)

**Comment by wongsyrone** [comment]
Good job.

**Comment by maz-1** [comment]
@Andy2244 

How about fixing multicall binary support ?
