### ISSUE TITLE
patch failed

### ISSUE THREAD

**Issue by cpexplorer** [wongsyrone/lede-1#27]
Applying ./patches/130-lzma_jffs2.patch using plaintext: 
patching file Makefile
Hunk #2 FAILED at 90.
1 out of 2 hunks FAILED -- saving rejects to file Makefile.rej
can't find file to patch at input line 23
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/jffsX-utils/compr.c
|+++ b/jffsX-utils/compr.c
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 44
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/jffsX-utils/compr.h
|+++ b/jffsX-utils/compr.h
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
patching file jffsX-utils/compr_lzma.c
patching file include/linux/jffs2.h
patching file include/linux/lzma.h
patching file include/linux/lzma/LzFind.h
patching file include/linux/lzma/LzHash.h
patching file include/linux/lzma/LzmaDec.h
patching file include/linux/lzma/LzmaEnc.h
patching file include/linux/lzma/Types.h
patching file jffsX-utils/lzma/LzFind.c
patching file jffsX-utils/lzma/LzmaDec.c
patching file jffsX-utils/lzma/LzmaEnc.c
can't find file to patch at input line 5014
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/jffsX-utils/mkfs.jffs2.c
|+++ b/jffsX-utils/mkfs.jffs2.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/130-lzma_jffs2.patch!

**Comment by wongsyrone** [comment]
删掉dl文件夹里旧的mtd-utils包
