### ISSUE TITLE
newifi d1 wan口和lan口反序

### ISSUE THREAD

**Issue by cpexplorer** [wongsyrone/lede-1#28]
编译出来的newifi d1固件存在wan和lan口反序问题导致无法拨号，请知悉；lede官方那边没找到反馈方法，所以....

**Comment by wongsyrone** [comment]
https://bugs.lede-project.org
如果汇报的信息不全的话一般会被直接关闭或者忽略。这部分代码我没改动过。

**Comment by cpexplorer** [comment]
lede官方也有这个问题

2016-11-18 6:37 GMT+08:00 白井黑子 notifications@github.com:
