### ISSUE TITLE
如何还原arch为mips_24kc?

### ISSUE THREAD

**Issue by cpexplorer** [wongsyrone/lede-1#29]
tl_wdr7500_v3固件，用这边的源码编译出来的固件arch变为mips_74kc了，请问如何修改为官方的mips_24kc？

**Comment by wongsyrone** [comment]
https://github.com/wongsyrone/lede-1/blob/master/target/linux/ar71xx/Makefile#L13

**Comment by cpexplorer** [comment]
哦哦，原来在这里啊，谢谢指教了
