### ISSUE TITLE
4.4.14 build error

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#3]
cp -fpR /home/ezhang/lede-1/build_dir/target-x86_64_musl-1.1.14/linux-x86_64/iptables-1.6.0/ipkg-install/usr/lib/libxtables.so\* /home/ezhang/lede-1/build_dir/target-x86_64_musl-1.1.14/linux-x86_64/iptables-1.6.0/ipkg-x86_64/libxtables/usr/lib/
cp -fpR /home/ezhang/lede-1/build_dir/target-x86_64_musl-1.1.14/linux-x86_64/iptables-1.6.0/extensions/libiptext.so /home/ezhang/lede-1/build_dir/target-x86_64_musl-1.1.14/linux-x86_64/iptables-1.6.0/ipkg-x86_64/libxtables/usr/lib/
find /home/ezhang/lede-1/build_dir/target-x86_64_musl-1.1.14/linux-x86_64/iptables-1.6.0/ipkg-x86_64/libxtables -name 'CVS' -o -name '.svn' -o -name '.#_' -o -name '_~'| xargs -r rm -rf
Package libxtables is missing dependencies for the following libraries:
libnetfilter_conntrack.so.3
libnfnetlink.so.0
make[3]: **\* [/home/ezhang/lede-1/bin/packages/x86_64/base/libxtables_1.6.0-1_x86_64.ipk] Error 1
make[3]: Leaving directory `/home/ezhang/lede-1/package/network/utils/iptables'
make[2]: *** [package/network/utils/iptables/compile] Error 2
make[2]: Leaving directory`/home/ezhang/lede-1'
make[1]: **\* [/home/ezhang/lede-1/staging_dir/target-x86_64_musl-1.1.14/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/ezhang/lede-1'
make: **\* [world] Error 2

**Comment by wongsyrone** [comment]
Don't use dnsmasq-full

**Comment by wongsyrone** [comment]
Also, please checkout 99a2b7f6f6d4f2276a089d4047cede0e4e0f6d53 since linux 4.4.14 and newly added BFS are under testing

**UPDATE:** linux 4.4.14 has many netfilter improvements while openwrt made lots of changes on it, will not update it atm.

**Comment by debiansid** [comment]
btw, I still can not boot x86-64 from CF card which x86-32 is good. openwrt was installed on sdb2

**Comment by wongsyrone** [comment]
Then report to the mailing list with details. I'm not using x86

**Comment by wongsyrone** [comment]
@debiansid 
I pushed a [fix](https://github.com/wongsyrone/lede-1/commit/8465eebcb57cf57840ad35cc3cdda7a9552c62f3), if all works as expected, you can build dnsmasq-full now.

**Comment by wongsyrone** [comment]
dnsmasq conntrack support should be fixed after https://github.com/wongsyrone/lede-1/commit/dc0446ca6a478e301698abce5be4995d0a2119f0 and https://github.com/wongsyrone/lede-1/commit/530983ce4be9b44c0a66bd6e1094f0acb299b102
