### ISSUE TITLE
lede 编译错误

### ISSUE THREAD

**Issue by dhsoft** [wongsyrone/lede-1#30]
CC      net/core/gen_estimator.o
  CC      net/core/net_namespace.o
  CC      net/core/secure_seq.o
  CC      net/core/flow_dissector.o
  CC      net/core/sysctl_net_core.o
  CC      net/core/dev.o
In file included from include/linux/linkage.h:6:0,
                 from include/linux/kernel.h:6,
                 from ./arch/mips/include/asm/uaccess.h:14,
                 from net/core/dev.c:75:
include/linux/export.h:65:20: error: redefinition of '__kstrtab_validate_xmit_skb_list'
  static const char __kstrtab_##sym[]   \
                    ^
include/linux/export.h:79:2: note: in expansion of macro '__EXPORT_SYMBOL'
  __EXPORT_SYMBOL(sym, "_gpl")
  ^
net/core/dev.c:2859:1: note: in expansion of macro 'EXPORT_SYMBOL_GPL'
 EXPORT_SYMBOL_GPL(validate_xmit_skb_list);
 ^
include/linux/export.h:65:20: note: previous definition of '__kstrtab_validate_xmit_skb_list' was here
  static const char __kstrtab_##sym[]   \
                    ^
include/linux/export.h:76:2: note: in expansion of macro '__EXPORT_SYMBOL'
  __EXPORT_SYMBOL(sym, "")
  ^
net/core/dev.c:2831:1: note: in expansion of macro 'EXPORT_SYMBOL'
 EXPORT_SYMBOL(validate_xmit_skb_list);
 ^
include/linux/export.h:70:39: error: redefinition of '__ksymtab_validate_xmit_skb_list'
  __visible const struct kernel_symbol __ksymtab_##sym \
                                       ^
include/linux/export.h:79:2: note: in expansion of macro '__EXPORT_SYMBOL'
  __EXPORT_SYMBOL(sym, "_gpl")
  ^
net/core/dev.c:2859:1: note: in expansion of macro 'EXPORT_SYMBOL_GPL'
 EXPORT_SYMBOL_GPL(validate_xmit_skb_list);
 ^
include/linux/export.h:70:39: note: previous definition of '__ksymtab_validate_xmit_skb_list' was here
  __visible const struct kernel_symbol __ksymtab_##sym \
                                       ^
include/linux/export.h:76:2: note: in expansion of macro '__EXPORT_SYMBOL'
  __EXPORT_SYMBOL(sym, "")
  ^
net/core/dev.c:2831:1: note: in expansion of macro 'EXPORT_SYMBOL'
 EXPORT_SYMBOL(validate_xmit_skb_list);
 ^
scripts/Makefile.build:258: recipe for target 'net/core/dev.o' failed
make[7]: *** [net/core/dev.o] Error 1
scripts/Makefile.build:403: recipe for target 'net/core' failed
make[6]: *** [net/core] Error 2
Makefile:961: recipe for target 'net' failed
make[5]: *** [net] Error 2
make[5]: Leaving directory '/home/dh/lede/source/build_dir/target-mipsel_24kc_musl-1.1.15/linux-ramips_mt7621/linux-4.4.35'
Makefile:26: recipe for target '/home/dh/lede/source/build_dir/target-mipsel_24kc_musl-1.1.15/linux-ramips_mt7621/linux-4.4.35/.image' failed
make[4]: *** [/home/dh/lede/source/build_dir/target-mipsel_24kc_musl-1.1.15/linux-ramips_mt7621/linux-4.4.35/.image] Error 2
make[4]: Leaving directory '/home/dh/lede/source/target/linux/ramips'
Makefile:13: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/dh/lede/source/target/linux'
target/Makefile:22: recipe for target 'target/linux/install' failed
make[2]: *** [target/linux/install] Error 2
make[2]: Leaving directory '/home/dh/lede/source'
target/Makefile:18: recipe for target '/home/dh/lede/source/staging_dir/target-mipsel_24kc_musl-1.1.15/stamp/.target_install' failed
make[1]: *** [/home/dh/lede/source/staging_dir/target-mipsel_24kc_musl-1.1.15/stamp/.target_install] Error 2
make[1]: Leaving directory '/home/dh/lede/source'
/home/dh/lede/source/include/toplevel.mk:194: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by wongsyrone** [comment]
我这边还没更上游的linux 4.4.35，所以应该是你那的问题

**Comment by dhsoft** [comment]
which ver?这个是https://github.com/openwrt-stuff/openwrt-mod引起的qosmon问题，或者是https://github.com/openwrt-stuff/openwrt-extra/tree/master/net引起的qos-gargoyle编译问题，qos-gargoyle、qosmon-gargoyle引起的，改了几次，这两个都编译没问题，就是在最终在dev.c的编译中出了问题。

**Comment by wongsyrone** [comment]
石像鬼需要你自己搞
