### ISSUE TITLE
能否提供samba 4.4编译好的ipk？WRT1900ACS v2

### ISSUE THREAD

**Issue by greekstreet** [wongsyrone/lede-1#31]
你好，我的路由器是wrt1900acs v2，刷的Chaos Calmer 15.05.01，用你的samba 4.4的包编译不出来。能否给我一个编译好的？我看你也用的wrt1900系列。我是纯小白，编译出错实在不知道怎么解决。

另外，不知道你有没有兴趣编译mysql 5.7。官方源里的5.1实在太老了。

谢谢。 :)

**Comment by wongsyrone** [comment]
如果编译的话请用基于Archlinux的系统，至于原因我也不太清楚。
而且我的win10不再显示samba的网络共享，我后来用了vsftpd替换，近期也没再跟踪samba上游的变化。
编译出来也很大，13MiB吧，我没用成功过，但是有人成功了，还给我发了修改过的init脚本和其他补丁。
基于文件大小和编译困难度，基本上没可能添加到上游。
