### ISSUE TITLE
Samba 4.4 doesn't compile on LEDE (head)

### ISSUE THREAD

**Issue by diizzyy** [wongsyrone/lede-1#32]
Hi,

Thanks for the awesome work being done. 
I tried getting Samba 4.4 compiling however it seems broken now. :-(

`
Build failed:
 -> task failed (err #2):
        {task: HEIMDAL_KX509_ASN1_ASN1 kx509.asn1 -> asn1_kx509_asn1.x,kx509_asn1.hx,kx509_asn1-priv.hx}
 -> task failed (err #2):
        {task: HEIMDAL_DIGEST_ASN1_ASN1 digest.asn1 -> asn1_digest_asn1.x,digest_asn1.hx,digest_asn1-priv.hx}
`

How to reproduce:

checkout latest lede and feeds repo (upstream)
replace lang/python with your version (you need to downgrade it to 2.7.12 otherwise it'll fail to apply patches).
Add samba44 and heimdal to package repo.

Tested on Marvell Armada 37x/38x/XP --> Linksys WRT3200ACM

Best regards, 
Daniel

**Comment by wongsyrone** [comment]
Please try Arch-based system and refer to https://github.com/wongsyrone/openwrt-1/issues/85

**Comment by wongsyrone** [comment]
And https://github.com/wongsyrone/openwrt-1/issues/73

**Comment by diizzyy** [comment]
Heimdal expects EGD which isn't in OpenSSL anymore.
Adding these patches fixes compilation.
https://svnweb.freebsd.org/ports?view=revision&revision=421928

**Comment by wongsyrone** [comment]
To be honest, I added samba 4.4 for better video streaming, but my Win10 won't show network sharing anymore. I replace it with vsftpd at last.

I'm not following Samba changes for a long time; you can check the last modified date of samba related stuff.

If you can find a way to bypass waf headache and reduce the binary size, we can get this upstream.

**Comment by wongsyrone** [comment]
Close due to inactive.

**Comment by ghost** [comment]
@wongsyrone 

Recently samba added --disable-python compile option. Would this help revive the package?

Reference:
Disabling Python Modules https://lists.samba.org/archive/samba-technical/2017-January/118218.html
https://github.com/samba-team/samba/pull/74

**Comment by wongsyrone** [comment]
Wow. I haven't touched this package for a long time. Python modules are run dependencies instead of the build system (a.k.a. waf)
