### ISSUE TITLE
patches 相关问题请教

### ISSUE THREAD

**Issue by pexcn** [wongsyrone/lede-1#37]
@wongsyrone dalao, 我最近折腾 lede, 遇到几个问题想请教一下：

### 关于 `git format-patch`

我看到 https://github.com/lede-project/source/tree/master/target/linux/ar71xx/patches-4.9 比如这种 patch，在 patch 文件的末尾都是不包含 git 版本号的，而默认 `git format-patch` 是带有 git 版本号的。

请问标准的方式是应该每次生成 patch 的时候都应该加上 `--no-signature` 这个参数吗？比如：

```bash
git format-patch HEAD~ --no-signature
```

### patch 刷新

像这种：https://github.com/wongsyrone/lede-1/commit/04d0c363e327b7e5a13a2e8ae519c234e1bd9a46 , 是如何做到补丁刷新的？

**Comment by wongsyrone** [comment]
一般都是直接format-patch出来的，有的版本号会丢失是因为以后的refresh patch。

刷新用 make target/linux/refresh V=99

**Comment by pexcn** [comment]
懂了，谢谢大佬。
