### ISSUE TITLE
make menuconfig 的疑问

### ISSUE THREAD

**Issue by pexcn** [wongsyrone/lede-1#38]
dalao, 请教一下，像这种：https://github.com/wongsyrone/lede-1/commit/a956226aa58d9f25dcb0c048bc8a4ee39170056e 修改，`make menuconfig` 里好像是没有的，这是在哪里生成的？

**Comment by wongsyrone** [comment]
make kernel_menuconfig

**Comment by pexcn** [comment]
嗯，谢谢dalao

**Comment by pexcn** [comment]
@wongsyrone 还想问下，如何才能修改 `target/linux/generic` 这里面的？
