### ISSUE TITLE
ddns update error

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#4]
Sun Jun 26 09:15:45 2016 daemon.err uhttpd[1556]: /usr/lib/ddns/dynamic_dns_lucihelper.sh: local: line 72: not in a function
Sun Jun 26 09:15:46 2016 daemon.err uhttpd[1556]: /usr/lib/ddns/dynamic_dns_lucihelper.sh: local: line 72: not in a function
Sun Jun 26 09:15:46 2016 daemon.err uhttpd[1556]: /usr/lib/ddns/dynamic_dns_lucihelper.sh: local: line 72: not in a function
Sun Jun 26 09:15:46 2016 daemon.err uhttpd[1556]: /usr/lib/ddns/dynamic_dns_lucihelper.sh: local: line 72: not in a function
Sun Jun 26 09:15:46 2016 daemon.err uhttpd[1556]: /usr/lib/ddns/dynamic_dns_lucihelper.sh: local: line 72: not in a function
Sun Jun 26 09:15:46 2016 daemon.err uhttpd[1556]: /usr/lib/ddns/dynamic_dns_lucihelper.sh: local: line 72: not in a function

**Comment by wongsyrone** [comment]
I have reported this to upstream, waiting for upstream fix
ref: https://github.com/openwrt/packages/issues/2885
