### ISSUE TITLE
luci-app-zerotier的“自动允许客户端NAT”没有按照预期工作

### ISSUE THREAD

**Issue by QiuSimons** [wongsyrone/lede-1#41]
luci-app-zerotier的“自动允许客户端NAT”没有按照预期工作，连入zerotier网络后，组员可以互相访问，但不能访问路由器下属的其他设备。
例：
router1为192.168.10.1
client1为192.168.10.2
router2为192.168.100.1
client1为192.168.100.2

client1可以访问router2，但是不能访问client2（可以ping通

log（不确定是不是异常情况）：
Thu May 26 14:06:50 2022 daemon.warn miniupnpd[11266]: HTTP peer [fd2f:fdb4:27c0::1]:40452 is not from a LAN, closing the connection
Thu May 26 14:06:50 2022 daemon.err zerotier-one[3915]: recv: Connection reset by peer
Thu May 26 14:06:50 2022 daemon.warn miniupnpd[11266]: HTTP peer [fd2f:fdb4:27c0::1]:40454 is not from a LAN, closing the connection
Thu May 26 14:06:50 2022 daemon.err zerotier-one[3915]: recv: Connection reset by peer
Thu May 26 14:06:50 2022 daemon.warn miniupnpd[11266]: HTTP peer [fd2f:fdb4:27c0::1]:40456 is not from a LAN, closing the connection
Thu May 26 14:06:50 2022 daemon.err zerotier-one[3915]: recv: Connection reset by peer

**Comment by wongsyrone** [comment]
nft和ipt两个版本都测试过，都可以访问。zerotier也需要用我修改的版本

**Comment by QiuSimons** [comment]
> nft和ipt两个版本都测试过，都可以访问。zerotier也需要用我修改的版本

感谢回复
22.03.0-rc2，纯nft模式，zerotier使用的是你的修改版本
如果你这边全部正常，那可能和ipv6有关
（话说有什么诊断方法么，或者我能如何提供更有效的log

**Comment by wongsyrone** [comment]
需要firewall配置和firewall status。

zt_auto_nat_pre_fwd和zt_auto_nat_post_rt确认已经成功创建。

另外log都打了tag，比如zerotier-hotplug和zerotier-init-script，利用logread程序可以筛选

**Comment by wongsyrone** [comment]
另外需要zerotier官网配置好路由

**Comment by QiuSimons** [comment]
> 另外需要zerotier官网配置好路由
![status](https://user-images.githubusercontent.com/45143996/170433804-a02a48d8-2caf-4043-b672-6277ec182717.jpg)
[log.txt](https://github.com/wongsyrone/lede-1/files/8776904/log.txt)
![nat](https://user-images.githubusercontent.com/45143996/170433818-d1a27dae-4fa4-40a2-9f28-86cb314bee30.jpg)

**Comment by QiuSimons** [comment]
> 你这里根本没有我脚本的tag的log

restart了一下服务
https://pastebin.com/BpVxCLuE

**Comment by wongsyrone** [comment]
`cat /etc/config/firewall`

**Comment by QiuSimons** [comment]
> `cat /etc/config/firewall`

https://pastebin.com/ppJp825K

**Comment by wongsyrone** [comment]
给你一个我的配置吧，你那个没法查是哪里的问题，插件太多，互相影响。

```
config defaults
	option input 'ACCEPT'
	option output 'ACCEPT'
	option fullcone '1'
	option synflood_protect '1'
	option forward 'DROP'
	option flow_offloading '0'
	option flow_offloading_hw '1'

config zone
	option name 'lan'
	list network 'lan'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'

config zone
	option name 'wan'
	list network 'wan'
	option input 'REJECT'
	option output 'ACCEPT'
	option forward 'REJECT'
	option fullcone '1'
	option masq '1'
	option mtu_fix '1'

config forwarding
	option src 'lan'
	option dest 'wan'

# We need to accept udp packets on port 68,
# see https://dev.openwrt.org/ticket/4108
config rule
	option name		Allow-DHCP-Renew
	option src		wan
	option proto		udp
	option dest_port	68
	option target		ACCEPT
	option family		ipv4

# Allow IPv4 ping
config rule
	option name		Allow-Ping
	option src		wan
	option proto		icmp
	option icmp_type	echo-request
	option family		ipv4
	option target		ACCEPT

config rule
	option name		Allow-IGMP
	option src		wan
	option proto		igmp
	option family		ipv4
	option target		ACCEPT

# Allow DHCPv6 replies
# see https://github.com/openwrt/openwrt/issues/5066
config rule
	option name		Allow-DHCPv6
	option src		wan
	option proto		udp
	option dest_port	546
	option family		ipv6
	option target		ACCEPT

config rule
	option name		Allow-MLD
	option src		wan
	option proto		icmp
	option src_ip		fe80::/10
	list icmp_type		'130/0'
	list icmp_type		'131/0'
	list icmp_type		'132/0'
	list icmp_type		'143/0'
	option family		ipv6
	option target		ACCEPT

# Allow essential incoming IPv6 ICMP traffic
config rule
	option name		Allow-ICMPv6-Input
	option src		wan
	option proto	icmp
	list icmp_type		echo-request
	list icmp_type		echo-reply
	list icmp_type		destination-unreachable
	list icmp_type		packet-too-big
	list icmp_type		time-exceeded
	list icmp_type		bad-header
	list icmp_type		unknown-header-type
	list icmp_type		router-solicitation
	list icmp_type		neighbour-solicitation
	list icmp_type		router-advertisement
	list icmp_type		neighbour-advertisement
	option limit		1000/sec
	option family		ipv6
	option target		ACCEPT

# Allow essential forwarded IPv6 ICMP traffic
config rule
	option name		Allow-ICMPv6-Forward
	option src		wan
	option dest		*
	option proto		icmp
	list icmp_type		echo-request
	list icmp_type		echo-reply
	list icmp_type		destination-unreachable
	list icmp_type		packet-too-big
	list icmp_type		time-exceeded
	list icmp_type		bad-header
	list icmp_type		unknown-header-type
	option limit		1000/sec
	option family		ipv6
	option target		ACCEPT

config rule
	option name		Allow-IPSec-ESP
	option src		wan
	option dest		lan
	option proto		esp
	option target		ACCEPT

config rule
	option name		Allow-ISAKMP
	option src		wan
	option dest		lan
	option dest_port	500
	option proto		udp
	option target		ACCEPT

config include 'miniupnpd'
	option type 'script'
	option path '/usr/share/miniupnpd/firewall.include'
	option family 'any'
	option reload '1'

config ipset
	option enabled '1'
	option reload_set '0'
	option counters '1'
	option comment '1'
	option name 'setmefree'
	option family 'ipv4'
	option match 'net'
	option timeout '0'
	list entry '91.108.4.0/22'
	list entry '91.108.56.0/22'
	list entry '109.239.140.0/24'
	list entry '149.154.164.0/22'
	list entry '149.154.168.0/21'

config ipset
	option enabled '1'
	option reload_set '0'
	option counters '1'
	option comment '1'
	option name 'setmefree6'
	option family 'ipv6'
	option match 'net'
	option timeout '0'
	list entry '2001:b28:f23f::/48'
	list entry '2001:b28:f23d::/48'
	list entry '2001:67c:4e8::/48'

config zone 'zt_zone_ztbto2fyg6'
	option network 'ztbto2fyg6'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
	option name 'zerotier'
	option masq '1'
	option mtu_fix '0'
	list device 'ztbto2fyg6'

config rule 'zt_rule_allowInbound'
	option name 'Allow-ZeroTier-Inbound'
	option src '*'
	option target 'ACCEPT'
	list proto 'all'
	option dest_port '9993'

config forwarding 'zt_fwd_ztbto2fyg62lan'
	option src 'zerotier'
	option dest 'lan'

config forwarding 'zt_fwd_ztbto2fyg62wan'
	option src 'zerotier'
	option dest 'wan'

config forwarding 'zt_fwd_lan2ztbto2fyg6'
	option src 'lan'
	option dest 'zerotier'

config rule 'zt_rule_allowSecondPort'
	option name 'Allow-ZeroTier-2ndPort'
	option src '*'
	option target 'ACCEPT'
	list proto 'all'
	option dest_port '42802'

config rule 'zt_rule_allowThirdPort'
	option name 'Allow-ZeroTier-3rdPort'
	option src '*'
	option target 'ACCEPT'
	list proto 'all'
	option dest_port '35276'
```

**Comment by QiuSimons** [comment]
> 你这是用了lean的openwrt了啊，还有
> 
> ```
> config include 'zerotier'
> 	option type 'script'
> 	option path '/etc/zerotier.start'
> 	option reload '1'
> ```
> 
> 还有
> 
> ```
> config include
> 	option path '/etc/firewall.user'
> ```
> 
> 这明显是fw3的遗留，还有一堆passwall啥的，根本不知道谁会改防火墙配置

用的官方openwrt，之前用的lean的luci，然后上nft以后发现问题，切换到了您这边的luci，遗留了配置
编译包含了ssrp passwall openclash

**Comment by QiuSimons** [comment]
> 给你一个我的配置吧，你那个没法查是哪里的问题，插件太多，互相影响。
> 
> ```
> config defaults
> 	option input 'ACCEPT'
> 	option output 'ACCEPT'
> 	option fullcone '1'
> 	option synflood_protect '1'
> 	option forward 'DROP'
> 	option flow_offloading '0'
> 	option flow_offloading_hw '1'
> 
> config zone
> 	option name 'lan'
> 	list network 'lan'
> 	option input 'ACCEPT'
> 	option output 'ACCEPT'
> 	option forward 'ACCEPT'
> 
> config zone
> 	option name 'wan'
> 	list network 'wan'
> 	option input 'REJECT'
> 	option output 'ACCEPT'
> 	option forward 'REJECT'
> 	option fullcone '1'
> 	option masq '1'
> 	option mtu_fix '1'
> 
> config forwarding
> 	option src 'lan'
> 	option dest 'wan'
> 
> # We need to accept udp packets on port 68,
> # see https://dev.openwrt.org/ticket/4108
> config rule
> 	option name		Allow-DHCP-Renew
> 	option src		wan
> 	option proto		udp
> 	option dest_port	68
> 	option target		ACCEPT
> 	option family		ipv4
> 
> # Allow IPv4 ping
> config rule
> 	option name		Allow-Ping
> 	option src		wan
> 	option proto		icmp
> 	option icmp_type	echo-request
> 	option family		ipv4
> 	option target		ACCEPT
> 
> config rule
> 	option name		Allow-IGMP
> 	option src		wan
> 	option proto		igmp
> 	option family		ipv4
> 	option target		ACCEPT
> 
> # Allow DHCPv6 replies
> # see https://github.com/openwrt/openwrt/issues/5066
> config rule
> 	option name		Allow-DHCPv6
> 	option src		wan
> 	option proto		udp
> 	option dest_port	546
> 	option family		ipv6
> 	option target		ACCEPT
> 
> config rule
> 	option name		Allow-MLD
> 	option src		wan
> 	option proto		icmp
> 	option src_ip		fe80::/10
> 	list icmp_type		'130/0'
> 	list icmp_type		'131/0'
> 	list icmp_type		'132/0'
> 	list icmp_type		'143/0'
> 	option family		ipv6
> 	option target		ACCEPT
> 
> # Allow essential incoming IPv6 ICMP traffic
> config rule
> 	option name		Allow-ICMPv6-Input
> 	option src		wan
> 	option proto	icmp
> 	list icmp_type		echo-request
> 	list icmp_type		echo-reply
> 	list icmp_type		destination-unreachable
> 	list icmp_type		packet-too-big
> 	list icmp_type		time-exceeded
> 	list icmp_type		bad-header
> 	list icmp_type		unknown-header-type
> 	list icmp_type		router-solicitation
> 	list icmp_type		neighbour-solicitation
> 	list icmp_type		router-advertisement
> 	list icmp_type		neighbour-advertisement
> 	option limit		1000/sec
> 	option family		ipv6
> 	option target		ACCEPT
> 
> # Allow essential forwarded IPv6 ICMP traffic
> config rule
> 	option name		Allow-ICMPv6-Forward
> 	option src		wan
> 	option dest		*
> 	option proto		icmp
> 	list icmp_type		echo-request
> 	list icmp_type		echo-reply
> 	list icmp_type		destination-unreachable
> 	list icmp_type		packet-too-big
> 	list icmp_type		time-exceeded
> 	list icmp_type		bad-header
> 	list icmp_type		unknown-header-type
> 	option limit		1000/sec
> 	option family		ipv6
> 	option target		ACCEPT
> 
> config rule
> 	option name		Allow-IPSec-ESP
> 	option src		wan
> 	option dest		lan
> 	option proto		esp
> 	option target		ACCEPT
> 
> config rule
> 	option name		Allow-ISAKMP
> 	option src		wan
> 	option dest		lan
> 	option dest_port	500
> 	option proto		udp
> 	option target		ACCEPT
> 
> config include 'miniupnpd'
> 	option type 'script'
> 	option path '/usr/share/miniupnpd/firewall.include'
> 	option family 'any'
> 	option reload '1'
> 
> config ipset
> 	option enabled '1'
> 	option reload_set '0'
> 	option counters '1'
> 	option comment '1'
> 	option name 'setmefree'
> 	option family 'ipv4'
> 	option match 'net'
> 	option timeout '0'
> 	list entry '91.108.4.0/22'
> 	list entry '91.108.56.0/22'
> 	list entry '109.239.140.0/24'
> 	list entry '149.154.164.0/22'
> 	list entry '149.154.168.0/21'
> 
> config ipset
> 	option enabled '1'
> 	option reload_set '0'
> 	option counters '1'
> 	option comment '1'
> 	option name 'setmefree6'
> 	option family 'ipv6'
> 	option match 'net'
> 	option timeout '0'
> 	list entry '2001:b28:f23f::/48'
> 	list entry '2001:b28:f23d::/48'
> 	list entry '2001:67c:4e8::/48'
> 
> config zone 'zt_zone_ztbto2fyg6'
> 	option network 'ztbto2fyg6'
> 	option input 'ACCEPT'
> 	option output 'ACCEPT'
> 	option forward 'ACCEPT'
> 	option name 'zerotier'
> 	option masq '1'
> 	option mtu_fix '0'
> 	list device 'ztbto2fyg6'
> 
> config rule 'zt_rule_allowInbound'
> 	option name 'Allow-ZeroTier-Inbound'
> 	option src '*'
> 	option target 'ACCEPT'
> 	list proto 'all'
> 	option dest_port '9993'
> 
> config forwarding 'zt_fwd_ztbto2fyg62lan'
> 	option src 'zerotier'
> 	option dest 'lan'
> 
> config forwarding 'zt_fwd_ztbto2fyg62wan'
> 	option src 'zerotier'
> 	option dest 'wan'
> 
> config forwarding 'zt_fwd_lan2ztbto2fyg6'
> 	option src 'lan'
> 	option dest 'zerotier'
> 
> config rule 'zt_rule_allowSecondPort'
> 	option name 'Allow-ZeroTier-2ndPort'
> 	option src '*'
> 	option target 'ACCEPT'
> 	list proto 'all'
> 	option dest_port '42802'
> 
> config rule 'zt_rule_allowThirdPort'
> 	option name 'Allow-ZeroTier-3rdPort'
> 	option src '*'
> 	option target 'ACCEPT'
> 	list proto 'all'
> 	option dest_port '35276'
> ```

好的，我测试下直接上你的配置

**Comment by wongsyrone** [comment]
你查查 ssrp passwall openclash 这几个插件有没有改防火墙的，据我所知老插件基本没怎么迁移到nftables，另外老fw3被官方放弃一方面是性能问题，一方面是本身bug太多，fw4只是生成nftables ruleset，比fw3不知道高到哪里去了。

**Comment by wongsyrone** [comment]
或者我给你个我编译的img，如果这个可以就排除我这里的bug了。

**Comment by wongsyrone** [comment]
有，等我上传

**Comment by QiuSimons** [comment]
> 你查查 ssrp passwall openclash 这几个插件有没有改防火墙的，据我所知老插件基本没怎么迁移到nftables，另外老fw3被官方放弃一方面是性能问题，一方面是本身bug太多，fw4只是生成nftables ruleset，比fw3不知道高到哪里去了。

有这个可能性，我这边排查下

**Comment by QiuSimons** [comment]
> 有，等我上传

感谢

**Comment by wongsyrone** [comment]
https://drive.google.com/drive/folders/1XjhWXMZHDgVBRw_YqpR_gIT5qBG2VhNg?usp=sharing

PS: 我上传就是zerotier远程开机，远程桌面上传的。

**Comment by QiuSimons** [comment]
> https://drive.google.com/drive/folders/1XjhWXMZHDgVBRw_YqpR_gIT5qBG2VhNg?usp=sharing
> 
> PS: 我上传就是zerotier远程开机，远程桌面上传的。

收到，晚点我虚拟机测试下，暂时先close这个issue了，目测是老插件的问题
顺带问一下，nftables的规则可以设置优先级么？我怀疑和优先级有关

**Comment by wongsyrone** [comment]
可以，你用 nft list ruleset 可以看到全部规则，里面的priority就是优先级，不同的type的优先级取值范围不同，需要学习nftables规则。

**Comment by QiuSimons** [comment]
> 可以，你用 nft list ruleset 可以看到全部规则，里面的priority就是优先级，不同的type的优先级取值范围不同，需要学习nftables规则。

https://pastebin.com/WwBafKSA
但看这张表，大概率是docker或者socat？（能这么断言么

**Comment by wongsyrone** [comment]
docker的问题概率大。socat是一个空chain，然后从input进来的都jump到这个空chain了，我记得默认policy是accept

**Comment by wongsyrone** [comment]
你可以按照官方/etc/nftables.d/里面给的例子，hook之后输出log和counter看一下是不是zt的都drop了

**Comment by QiuSimons** [comment]
> 你可以按照官方/etc/nftables.d/里面给的例子，hook之后输出log和counter看一下是不是zt的都drop了

好的，我看一下，感谢您的帮助
