### ISSUE TITLE
编译失败ERROR: package/external/openwrt-fullconenat failed to build.

### ISSUE THREAD

**Issue by skill7899** [wongsyrone/lede-1#42]
ibipt_FULLCONENAT.c:(.text+0x42c): multiple definition of `_init'; /data/cpl/lede-1/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/11.3.0/../../../../x86_64-openwrt-linux-musl/lib/crti.o:/data/cpl/lede-1/build_dir/toolchain-x86_64_gcc-11.3.0_musl/musl-1.2.3/crt/x86_64/crti.s:4: first defined here
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:2: libipt_FULLCONENAT.so] Error 1
make[4]: Leaving directory '/data/cpl/lede-1/build_dir/target-x86_64_musl/linux-x86_64/fullconenat-2022-02-13-108a36cb'
make[3]: *** [Makefile:71: /data/cpl/lede-1/build_dir/target-x86_64_musl/linux-x86_64/fullconenat-2022-02-13-108a36cb/.built] Error 2
make[3]: Leaving directory '/data/cpl/lede-1/package/external/openwrt-fullconenat'
time: package/external/openwrt-fullconenat/compile#2.11#0.38#5.93
    ERROR: package/external/openwrt-fullconenat failed to build.
make[2]: Leaving directory '/data/cpl/lede-1'
make[1]: Leaving directory '/data/cpl/lede-1'

**Comment by wongsyrone** [comment]
This is deprecated as I'm using nft-fullcone now
