### ISSUE TITLE
fping or smokeping on lede-1

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#5]
Hi
is there any chance to port those into lede-1?

**Comment by wongsyrone** [comment]
It seems fping can be ported, smokeping is mainly written in perl, you need to install perl package and try to execute it.

Any use cases?

**Comment by debiansid** [comment]
I want to monitor my vps from gateway.

**Comment by wongsyrone** [comment]
a shell script would be better on router

**Comment by debiansid** [comment]
I agree, but mine is x86 based , so performance is not my concern.

**Comment by wongsyrone** [comment]
fping will be under low priority, without guarantee.

**Comment by debiansid** [comment]
got it, thanks.I can just copy fping binary from alpine linux x86 to my x86 based lede-1 for now.
ps, or you can fork alpine linux to your "lede-2", which is dedicate to x86 based router.
