### ISSUE TITLE
﻿git pull error

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#7]
﻿git pull
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by wongsyrone** [comment]
I did a git rebase several days ago. Please backup your local changes and `git reset --hard <hash>` to a very old commit, then you can use `git pull` to fast-forward to latest git HEAD.

Sorry for inconvenience.

**Comment by wongsyrone** [comment]
another "simple" way to solve this conflict is to re-clone the whole repo.

Make sure to backup dl/ folder and your local changes.

**Comment by debiansid** [comment]
ok, I fixed it.thanks
