### ISSUE TITLE
building error 

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#8]
﻿make[3]: Entering directory '/home/storage/lede-1/package/network/config/netifd'
mkdir -p /home/storage/lede-1/dl
SHELL= flock /home/storage/lede-1/tmp/.netifd-2016-07-29-656c387974879105c2aaec6b62478d0195067f2d.tar.gz.flock -c '      echo "Checking out files from the git repository..."; mkdir -p /home/storage/lede-1/tmp/dl && cd /home/storage/lede-1/tmp/dl && rm -rf netifd-2016-07-29 && [ ! -d netifd-2016-07-29 ] && git clone --depth 5 https://git.lede-project.org/project/netifd.git netifd-2016-07-29 && (cd netifd-2016-07-29 && git checkout 656c387974879105c2aaec6b62478d0195067f2d && git submodule update --init --recursive) && echo "Packing checkout..." && rm -rf netifd-2016-07-29/.git &&   tar czf /home/storage/lede-1/tmp/dl/netifd-2016-07-29-656c387974879105c2aaec6b62478d0195067f2d.tar.gz netifd-2016-07-29 && mv /home/storage/lede-1/tmp/dl/netifd-2016-07-29-656c387974879105c2aaec6b62478d0195067f2d.tar.gz /home/storage/lede-1/dl/ && rm -rf netifd-2016-07-29; '
Checking out files from the git repository...
Cloning into 'netifd-2016-07-29'...
remote: Counting objects: 68, done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 68 (delta 16), reused 23 (delta 1)
Unpacking objects: 100% (68/68), done.
Checking connectivity... done.
fatal: reference is not a tree: 656c387974879105c2aaec6b62478d0195067f2d
Makefile:46: recipe for target '/home/storage/lede-1/dl/netifd-2016-07-29-656c387974879105c2aaec6b62478d0195067f2d.tar.gz' failed
make[3]: **\* [/home/storage/lede-1/dl/netifd-2016-07-29-656c387974879105c2aaec6b62478d0195067f2d.tar.gz] Error 128
make[3]: Leaving directory '/home/storage/lede-1/package/network/config/netifd'
package/Makefile:124: recipe for target 'package/network/config/netifd/compile' failed
make[2]: **\* [package/network/config/netifd/compile] Error 2
make[2]: Leaving directory '/home/storage/lede-1'
package/Makefile:121: recipe for target '/home/storage/lede-1/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile' failed
make[1]: **\* [/home/storage/lede-1/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/storage/lede-1'
/home/storage/lede-1/include/toplevel.mk:193: recipe for target 'world' failed
make: **\* [world] Error 2

**Comment by wongsyrone** [comment]
修改这行https://github.com/wongsyrone/lede-1/blob/master/include/download.mk#L95 的depth后面的5为50
