### ISSUE TITLE
shadowsocks-libev 2.4.8 error

### ISSUE THREAD

**Issue by debiansid** [wongsyrone/lede-1#9]
install -d -m0755 /home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/ipkg-i386_pentium4/shadowsocks-libev/usr/bin
install -m0755 /home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/src/ss-{local,redir,tunnel} /home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/ipkg-i386_pentium4/shadowsocks-libev/usr/bin
find /home/storage/lede-1/build_dir/target-i386_pentium4_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.4.8/ipkg-i386_pentium4/shadowsocks-libev -name 'CVS' -o -name '.svn' -o -name '.#_' -o -name '_~'| xargs -r rm -rf
Package shadowsocks-libev is missing dependencies for the following libraries:
libz.so.1
Makefile:83: recipe for target '/home/storage/lede-1/bin/packages/i386_pentium4/base/shadowsocks-libev_2.4.8-3_i386_pentium4.ipk' failed
make[3]: **\* [/home/storage/lede-1/bin/packages/i386_pentium4/base/shadowsocks-libev_2.4.8-3_i386_pentium4.ipk] Error 1
make[3]: Leaving directory '/home/storage/lede-1/package/openwrt-shadowsocks'
package/Makefile:124: recipe for target 'package/openwrt-shadowsocks/compile' failed
make[2]: **\* [package/openwrt-shadowsocks/compile] Error 2
make[2]: Leaving directory '/home/storage/lede-1'
package/Makefile:121: recipe for target '/home/storage/lede-1/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile' failed
make[1]: **\* [/home/storage/lede-1/staging_dir/target-i386_pentium4_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/storage/lede-1'
/home/storage/lede-1/include/toplevel.mk:193: recipe for target 'world' failed
make: **\* [world] Error 2

**Comment by debiansid** [comment]
added +zlib into DEPENDS:=
fixed

**Comment by wongsyrone** [comment]
我是编译的mbedtls版本，zlib应该是openssl带来的
